name: Ansible Lint

on:
  pull_request:
    paths:
      - "playbooks/**"
      - "roles/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Run ansible-lint
        run: ansible-lint playbooks/
